### ISSUE TITLE
[FeatureRequest] Use PyBullet Client ID to enable multiple pybullet instances

### ISSUE THREAD

**Issue by mees** [facebookresearch/tacto#1]
Currently the Sensor class doesn't accept a cid as input parameter [0]. For cases where one wants to have multiple pybullet instances / threads, using the cid would be a simple way to allow it.

[0] https://github.com/facebookresearch/tacto/blob/master/tacto/sensor.py#L52

**Comment by poweic** [comment]
Hi @mees,

Thank you for submitting the first feature request!

Yes, adding a cid would be a quick and simple way to allow users to have multiple pybullet instances. Would you like to submit a pull request? If not, I can work on this.

**Comment by mees** [comment]
Hi @poweic,
I just created a PR, let me know if its ok.
