### ISSUE TITLE
How to enable shadows in Tacto?

### ISSUE THREAD

**Issue by chenwh14** [facebookresearch/tacto#10]
Hi,
I read your paper and was impressed by the realistic readings generated by Tacto. You mentioned in the paper that shadows can be easily enabled in Tacto, so I tried with changing the 515th line in [renderer.py](https://github.com/facebookresearch/tacto/blob/master/tacto/renderer.py):
    ```
     color, depth = self.r.render(self.scene, flags=RenderFlags.SHADOWS_ALL)
    ```
However,  pyrender 0.1.45 seems not to support shadows for point lights. An exception is thrown:
```
NotImplementedError: Shadows not implemented for point lights
```
Could you help me find the way to enable shadows in Tacto?
Thank you!

**Comment by wx405557858** [comment]
Hi, yes, in order to enable shadow, we changed the light source to [Directional Light](https://pyrender.readthedocs.io/en/latest/generated/pyrender.light.DirectionalLight.html). We will update the version with shadow support soon! Sorry for the wait!

**Comment by gabrielecaddeo** [comment]
Hi, 
any news about the shadows?

**Comment by gabrielecaddeo** [comment]
Hi @wx405557858,
Are there any news about the shadows?
