### ISSUE TITLE
PyTables error in experiments/grasp_stability/grasping_data_collection.py

### ISSUE THREAD

**Issue by shivanimall** [facebookresearch/tacto#15]
I ran setup.py and installed all additional requirements before running each package, but getting this error. I tried doing `pip install tables` which did not fix the issue. both in draw.py and above file, deepdish is used which depends on pytables

```Traceback (most recent call last):
  File "/Users/shivanimall/tacto/experiments/grasp_stability/draw.py", line 62, in <module>
    mean, std = load(field, Ns, epoch=epoch)
  File "/Users/shivanimall/tacto/experiments/grasp_stability/draw.py", line 27, in load
    log = dd.io.load(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deepdish/io/__init__.py", line 14, in _f
    raise ImportError("You need PyTables for this function")
ImportError: You need PyTables for this function
```

**Comment by shivanimall** [comment]
also for my issue posted in #12 I found this https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x pybulletX was likely tested on unix only?

**Comment by wx405557858** [comment]
Hi @shivanimall , looks like it PyTables hasn't been supported well on python3.9. I tested it on python3.8, and ``pip install deepdish`` works well.

**Comment by shivanimall** [comment]
thanks @wx405557858 alternatively, I was planning to save these maps in npy arrays, hoping that will work too.
