### ISSUE TITLE
control digit touch movements on an object 

### ISSUE THREAD

**Issue by shivanimall** [facebookresearch/tacto#18]
Hello,

wanted to share some background I am using tacto for and hoping to get your thoughts/suggestions on the best ways about this:

I modified the robot in https://github.com/facebookresearch/tacto/blob/master/experiments/grasp_stability/robot.py to have only one finger tip (i.e deleted the left finger in `setup/sawyer_wsg50.urdf`) and instead of `grasp` or `reach` as in https://github.com/facebookresearch/tacto/blob/master/experiments/grasp_stability/grasp_data_collection.py#L246,  trying to perform a `touch` on an object(is static) using digit **but** with very close accuracy for the touch location/position on the object.

My end goal is to make the finger_right_tip on end effector reach a desired base position with close accuracy( at least upto one decimal) on the static object so that I can obtain rgb, depth map touch readings for the desired touch/collision point.
Currently using `go` function in `robot.py` does not get me this accuracy which is central to my use case. 
another caveat I found -- using the robot arm requires accounting for exact rotation/euler values to reach a desired location.

Some thoughts I have are to
1/ change/simplify robot structure
2/ use a different type of end effector
3/ currently I keep object static and move the digit. but maybe can do the reverse of this-  control object movements (via grasp/lift) and bring in contact  w/ a static digit touch sensor 
4/ the surface area of digit tip also matters since that will determine the maximum covered region of the given touch location. (want it to be small for accuracy)

maybe physics related, but is there a simple way/api in tacto to perform touch on different desired points on an object?

Please let me know if my question is unclear. Thank you so much!

**Comment by wx405557858** [comment]
Hi @shivanimall, the directions look reasonable to me! The robot arm control is using pybullet IK solver to reach a goal pose, maybe not accurate enough for your requirement (the real robot might have similar precision errors for IK). But for simplification, I think an extreme simplification would be moving a single sensor to touch the object without the robot arm. That might make it easier to start. Hope it helps!

**Comment by shivanimall** [comment]
thanks much @wx405557858!
will try this out and update as I run into issues.

**Comment by shivanimall** [comment]
a quick followup, when you say moving a single sensor to touch without robot arm- how would you simulate the movement?
using `pb.getContactPoints` would not work since it does not allow me control which point I want to move to (asked here: https://github.com/bulletphysics/bullet3/discussions/3804)
so from my understanding, I would have to rely on `pb.setJointControlArray` and pybullet's IK to control specifying points even in the simplest robot structure. please let me know if you have other suggestions @wx405557858 thanks.
