### ISSUE TITLE
omnitact sensor finger base STL support

### ISSUE THREAD

**Issue by shivanimall** [facebookresearch/tacto#20]
Hello, 

I see that the onmitact sensor and the base are  mounted together: (https://github.com/facebookresearch/tacto/blob/master/meshes/omnitact.STL) but similar to following where `finger_tip`/`finger_base` use separate STL files here: https://github.com/facebookresearch/tacto/blob/master/experiments/grasp_stability/setup/robots/sawyer_wsg50.urdf#L582
and  https://github.com/facebookresearch/tacto/blob/master/experiments/grasp_stability/setup/robots/sawyer_wsg50.urdf#L633

for my usecase as well, I'm hoping to build something similar but using omnitact sensor (with finger base and finger tip)
So wondering if you could help me with 2 seperate STL files for omnitact sensor (one for finger base and one for finger tip) like digit?

unlike here: https://github.com/facebookresearch/tacto/blob/master/meshes/omnitact.urdf, I'd have to link finger tip and finger base via a joint as above.

please let me know if my question is unclear. thank you!

**Comment by wx405557858** [comment]
Hi @shivanimall, 

Is there any reason for splitting the `finger_tip and finger_base` and link them via a joint? From my information, the current omnitact is designed as a whole sensor including the bottom plate.

The finger_base for the DIGIT is a connector for attaching the sensor to different grippers/hands. If you want to also attach the omnitact to the gripper, you could design a similar CAD (from omnitact bottom part to the gripper), and link them together via a joint. (The bottom holes for omnitact is 3.5mm in diameter, and 34 mm between the centers of holes.) Then it should be the same structure as sawyer_wsg50.urdf.
