### ISSUE TITLE
experiments/grasp_stability/train.py TypeError

### ISSUE THREAD

**Issue by lxiaol21** [facebookresearch/tacto#23]
Hello

I have collected the data and encountered a problem when running train.py. How can I save it?

thank you
![11111](https://user-images.githubusercontent.com/71709018/121522685-f18cbd80-ca27-11eb-93ff-2636f7108f60.png)

**Comment by wx405557858** [comment]
Hi @lxiaol21 ,

Looks like a dimension problem. Would you mind putting some debugging info there? 

e.g. printing the d before this line: https://github.com/facebookresearch/tacto/blob/d9b6a8bddd83af40f4e65e08da5ce55790c4f2a5/experiments/grasp_stability/train.py#L73

either
`print(d)`
or
`print(d.shape)`

**Comment by lxiaol21** [comment]
![1](https://user-images.githubusercontent.com/71709018/121657955-78e33b00-cad3-11eb-95b2-f98ce0ee17d3.png)
![2](https://user-images.githubusercontent.com/71709018/121657953-77b20e00-cad3-11eb-9598-4137be0ee5f7.png)
![3](https://user-images.githubusercontent.com/71709018/121657947-7680e100-cad3-11eb-83a4-af946d02658b.png)
![4](https://user-images.githubusercontent.com/71709018/121657938-754fb400-cad3-11eb-8db3-c5122ed9072b.png)
![5](https://user-images.githubusercontent.com/71709018/121657924-72ed5a00-cad3-11eb-83e2-0b566e75bfc5.png)

Hello

I have found the reason for the above problem, which is in the data I collected

The data types of "visioncolor" and "visiondepth" are wrong. The results of other data print (d.shape) are (320,240,,3). When k = visioncolor or K = visiondepth, the results of print (d.shape) are different（ p1,p2,p3）

So I changed grasp_ data_ collection.py（p4）

But after I modified it, I collected the data again, and new problems appeared. Is there any mistake in my modification? How can I solve it（ p5）

**Comment by lxiaol21** [comment]
![Uploading 222222.png…]()

**Comment by wx405557858** [comment]
Hi @lxiaol21 ,

Got it, it should be caused by the dtype. How about assigning the dtype when creating the array? 
say:
`np.array(rgb)`
change to
`np.array(rgb, dtype=np.uint8)`

**Comment by lxiaol21** [comment]
The problem is solved. Thank you very much
