### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by mees** [facebookresearch/tacto#24]
Hi all,
the currently release pypi Tacto package dates December 16, 2020. Would it be possible to build and upload a newer version of Tacto to Pypi to have included the fixes that have been intorduced since then?
Best,
Oier

**Comment by wx405557858** [comment]
Hi @robertocalandra , would you mind publishing an updated Pypi tacto release? Thank you so much!

**Comment by AlphaBetaPhi** [comment]
Hi @mees,

The latest version has been uploaded to PyPi.
