### ISSUE TITLE
Fail to create a GelSight around a cylinder

### ISSUE THREAD

**Issue by jc-bao** [facebookresearch/tacto#32]
Hi, everyone. I am trying to create a GelSight in a cylinder. I try to write a sensor configuration file according to the `OmniContact` example. But the result turns out to be a blank image. [Here](https://github.com/jc-bao/roller_grasper_tacto/blob/main/assets/sensors/roller.yml) is the link to my sensor configuration file. 

|A simple demonstration to the sensor|Gelsight image|
|-|-|
|<img width="764" alt="image" src="https://user-images.githubusercontent.com/60093981/180343944-5704c51a-e2b2-43b7-be4e-c36484603918.png">|<img width="266" alt="image" src="https://user-images.githubusercontent.com/60093981/180344053-43ba4872-2345-470f-ad09-bdf99e4296ca.png">|

What could lead to that error? Any information will be highly appreciated!

**Comment by wx405557858** [comment]
Hi @jc-bao,
Yeah, it may need some tuning for setting up new sensors. The orientation can be tricky. 

For debugging, it is highly recommended to temporarily replace the offscreen rendering to the on-screen viewer to see the whole sensor mesh and camera view in PyRender with an interactive window. This helps adjusts the setting to the desired poses.

In TACTO, the offscreen rendering is around here:
https://github.com/facebookresearch/tacto/blob/a21d0c4626d74a546d94859226c2fea348babb6a/tacto/renderer.py#L568

For on-screen viewer, the PyRender document is here:
https://pyrender.readthedocs.io/en/latest/api/index.html#on-screen-viewer

**Comment by jc-bao** [comment]
Thanks for that advice! 
It seems that this is caused by a solid mesh file. After skeletonizing the model, rendering works fine. But when the object touches the Gelsight, the gel sight behaves weirdly. There is a blue light blink. 
<img width="764" alt="image" src="https://media0.giphy.com/media/tG3iJIfaAyfnrWdjQP/giphy.gif?cid=790b761180d09e86410a15b595b58234ffa68565b8af136e&rid=giphy.gif&ct=g">

**Comment by jc-bao** [comment]
I think I have solved this problem by defining the different mesh in the sensor and robot models.
In the robot URDF model, I use the solid model. For the mesh in sensor configuration, I use the hollow model, which only contains the surface. 
The previous problem might be caused by the small thickness of the object's surface.
