### ISSUE TITLE
No tactile feedback for some objects

### ISSUE THREAD

**Issue by lukashermann** [facebookresearch/tacto#9]
Hi, 
I am trying to use tacto for a door opening task, but I don't get a tactile feedback when grasping the handle. 

![handle](https://user-images.githubusercontent.com/23167230/105188623-62dcda00-5b34-11eb-9d9d-4cd8e3238e7f.png)
![handle_img](https://user-images.githubusercontent.com/23167230/105188645-67a18e00-5b34-11eb-8e90-5b2be2247c47.png)

For other objects like this banana it works well:

![banana](https://user-images.githubusercontent.com/23167230/105188903-aa636600-5b34-11eb-8c91-bec9d4a0fec6.png)
![banana_img](https://user-images.githubusercontent.com/23167230/105188906-ab949300-5b34-11eb-8d17-8f8fa1066c61.png)

Do you have any idea what could cause this problem? I made sure that the door object is added to the digit sensor.
This is the mesh of the door: 

![Screenshot from 2021-01-20 15-19-33](https://user-images.githubusercontent.com/23167230/105189072-e0a0e580-5b34-11eb-8d72-6880ac604b16.png)

I took the digit fingers from demo_pybullet_grasp.py and added them to our panda gripper.

Thank you!

**Comment by wx405557858** [comment]
Hi @lukashermann, thank you for the feedback. Could you try examples/demo_pybullet_digit.py, and replace the sphere object with the door object, and drag the object around? It's the simplest environment to test signals. Is there any signal when the sensor is touching the door/handle?

**Comment by wx405557858** [comment]
hi @lukashermann, could you share the urdf file & code with us, so we could look into it? thanks!

**Comment by wx405557858** [comment]
Close the issue for no further information, please reopen it if you encounter similar issues! Thanks!

**Comment by Rennylex** [comment]
I encountered the same issue, Is there a solution?
